### ISSUE TITLE
forms: feedback button hides submit button

### ISSUE THREAD

**Issue by aduermael** [Ni-ft/dashboard#4]
![screen shot 2017-05-24 at 2 53 06 pm](https://cloud.githubusercontent.com/assets/6775074/26427346/30a25e14-4091-11e7-88a8-2237174e0542.png)

In this case the "Add User" button is partially hidden. 

IMHO the cancel / submit buttons shouldn't be placed all the way down. Right below the form would be better.

**Comment by TimDum** [comment]
@bassem-limem we should maybe put the feedback elsewhere and link it to our issue button in this repo on github, what do you think ?
